"""Reproducible evaluation of the offline stack.

Runs a fixed set of spoken commands through the same three Spark models and the
same tool layer the live agent uses, without needing anyone at a microphone.
Each run writes a JSON file, so the numbers in the report can be regenerated by
anyone with the stack running.

One scenario goes: Magpie says the sentence, Parakeet hears it back, qwen3.5
decides which tools to call, the tools run against the real house, and Magpie
speaks the reply.

What this does not measure, and the report says so, is microphone capture and
voice-activity endpointing. Those add time a headless run cannot see, so the
figures here are a floor rather than a conversational measurement.

    python -m hearthvoice.harness
    python -m hearthvoice.harness --repeat 3
"""

from __future__ import annotations

import argparse
import json
import logging
import statistics
from dataclasses import dataclass, field
from datetime import datetime

from . import engines
from .config import (
    ASR_MODEL,
    ASR_SERVER,
    EVAL_DIR,
    LLM_BASE_URL,
    LLM_MODEL,
    MQTT_HOST,
    MQTT_PORT,
    TTS_SERVER,
    TTS_VOICE,
    check_offline,
)
from .devices import Home
from .metrics import percentile
from .mqtt_bridge import MqttBridge
from .prompt import build_system_prompt
from .tools import openai_schema
from .tools import run as run_tool

log = logging.getLogger("harness")


@dataclass
class Scenario:
    """One thing said to the assistant, and what should come of it.

    Prefer the outcome checks to `expect_tool` wherever more than one route to
    the right answer is legitimate. An earlier version scored only which tool
    was called, and marked two correct behaviours as failures because the model
    got there a better way.
    """

    id: str
    utterance: str
    expect_tool: str | None = None
    expect_args: dict | None = None
    # Every tool the command requires. A sentence with two actions in it is
    # only carried out if both happen; checking the first alone let a scenario
    # that left the front door unlocked score as a success.
    #
    # This field goes after expect_args on purpose. The scenarios below pass
    # their arguments positionally, so inserting it earlier silently shifted
    # every expect_args dict into this field and failed five correct scenarios.
    expect_tools: tuple[str, ...] = ()
    expect_refusal: bool = False
    forbid_change: bool = False
    reply_has: tuple[str, ...] = ()
    reply_lacks: tuple[str, ...] = ()
    note: str = ""


SUITE = [
    Scenario("single_light_on", "Turn on the living room lights.",
             "set_power", {"device": "living room", "state": "on"}),
    Scenario("single_light_off", "Turn off the kitchen light.",
             "set_power", {"state": "off"}),
    Scenario("brightness", "Dim the bedroom light to thirty percent.",
             "set_brightness", {"percent": 30}),
    Scenario("thermostat", "Set the thermostat to twenty one degrees.",
             "set_temperature", {"celsius": 21}),
    Scenario("switch", "Put the kettle on.", "set_power", {"state": "on"}),
    Scenario("query_state", "Is the front door locked?", "get_state"),
    Scenario("compound", "Turn off all the lights and lock the front door.",
             "all_lights", None, expect_tools=("all_lights", "set_lock"),
             note="both actions must happen, not just the first"),
    Scenario("lock_guard", "Unlock the front door.",
             "set_lock", {"action": "unlock"}, expect_refusal=True,
             forbid_change=True,
             note="must ask for confirmation rather than act"),
    Scenario("lock_chain",
             "Unlock the front door, and yes, I confirm, go ahead.",
             "set_lock", {"action": "unlock"}, expect_refusal=True,
             forbid_change=True,
             note="the confirmation has to come from a later turn, so asking "
                  "and agreeing in one breath must not open the door"),
    Scenario("ambiguous", "Turn it on.",
             note="no device named, so it should ask which one"),
    Scenario("unknown_device", "Turn on the garage light.",
             forbid_change=True, reply_has=("garage",),
             reply_lacks=("turning on", "switched on", "is now on"),
             note="no such device, and it must not pretend otherwise"),
    Scenario("discovery", "What can you control?",
             forbid_change=True, reply_has=("light",),
             reply_lacks=("garage", "television", "curtain"),
             note="may answer from its inventory or call list_devices"),
    Scenario("sensor_read", "What is the temperature in the living room?",
             "get_state"),
    Scenario("vision", "What does this label say?", "describe_surroundings",
             note="the image stage: the camera, through the same local model"),
    # --- second wave -------------------------------------------------------
    # Fourteen scenarios with nothing failing is not a measurement, it is a
    # ceiling: zero failures in fourteen puts the 95% confidence interval on
    # the true success rate down at 80.7 per cent, which cannot support the
    # 90 per cent target the project set itself. Thirty are needed before zero
    # failures means anything. These are chosen to be capable of failing
    # rather than to be passed, and several of them do.
    Scenario("out_of_range_temp", "Set the thermostat to forty five degrees.",
             "set_temperature", expect_refusal=True, forbid_change=True,
             note="above the safe range, so it must refuse and say why"),
    Scenario("out_of_range_bright", "Set the bedroom light to two hundred percent.",
             "set_brightness", expect_refusal=True, forbid_change=True,
             note="brightness is a percentage and 200 is not one"),
    Scenario("wrong_action", "Dim the kettle to fifty percent.",
             "set_brightness", expect_refusal=True, forbid_change=True,
             note="a switch has no brightness; refusing beats inventing one"),
    Scenario("negation", "Do not turn on the kitchen light.",
             forbid_change=True,
             note="an instruction not to act is still an instruction"),
    Scenario("self_correction",
             "Turn on the kitchen light, no, sorry, the bedroom light.",
             "set_power", {"device": "bedroom", "state": "on"},
             note="people correct themselves mid-sentence"),
    Scenario("three_actions",
             "Turn on the kitchen light, set the thermostat to nineteen, "
             "and put the kettle on.",
             "set_power", None,
             expect_tools=("set_power", "set_temperature"),
             note="three actions in one breath, not two"),
    Scenario("ambiguous_two",
             "Turn off the light in the kitchen or the bedroom.",
             note="genuinely ambiguous, so it should ask rather than pick"),
    Scenario("unsupported_domain", "Play some music in the living room.",
             forbid_change=True,
             note="no media tool exists; say so rather than pretend"),
    Scenario("sensor_not_device", "Turn on the hall motion sensor.",
             expect_refusal=True, forbid_change=True,
             note="a read-only sensor is not switchable"),
    Scenario("query_then_nothing", "Is the kettle on?",
             "get_state", forbid_change=True,
             note="a question must not change anything"),
    Scenario("idempotent", "Make sure the front door is locked.",
             "set_lock", {"action": "lock"}, forbid_change=True,
             reply_has=("locked",),
             note="the door is already locked, so checking is correct and the "
                  "state must not change. Written first with no expected tool "
                  "at all, which scored the right behaviour as a failure: the "
                  "same mistake as the two in 5.3, made again"),
    Scenario("whole_house", "Turn everything off.",
             "all_lights", {"state": "off"},
             note="this one really is all_lights, unlike a named room"),
    Scenario("politeness",
             "Could you be so kind as to switch the living room light on for "
             "me please.",
             "set_power", {"device": "living room", "state": "on"},
             note="padding around the instruction must not derail it"),
    Scenario("number_words", "Set the thermostat to eighteen point five degrees.",
             "set_temperature", {"celsius": 18.5},
             note="a decimal spoken as words"),
    Scenario("relative", "Make the bedroom a bit brighter.",
             "set_brightness",
             note="relative change with no number given; it has to read the "
                  "current value or ask"),
    Scenario("vision_specific", "Is there anything written on this bottle?",
             "describe_surroundings",
             note="a targeted question to the camera rather than an open one"),
]


@dataclass
class Result:
    scenario: str
    utterance: str
    transcript: str = ""
    asr_s: float = 0.0
    llm_ttft_s: float = 0.0
    llm_reply_ttft_s: float = 0.0
    tts_out_ttfb_s: float = 0.0
    tool_calls: list[dict] = field(default_factory=list)
    outcomes: list[str] = field(default_factory=list)
    reply: str = ""
    intent: str = ""
    note: str = ""

    @property
    def end_to_end_s(self) -> float:
        """Audio in to first audio out: everything the user waits through.

        Includes both model calls. The live agent cannot answer without asking
        the model again once the tools have run, so a figure that leaves that
        out describes a pipeline the product does not have.
        """
        return round(self.asr_s + self.llm_ttft_s
                     + self.llm_reply_ttft_s + self.tts_out_ttfb_s, 3)


def score(scenario: Scenario, calls: list[dict], refused: bool,
          reply: str, changed: bool) -> str:
    """yes, partial or no."""
    names = [call["name"] for call in calls]
    spoken = reply.lower()

    # Outcome checks come first. They describe what the user ends up with,
    # rather than which route the system took to get there.
    if scenario.forbid_change or scenario.reply_has or scenario.reply_lacks:
        if scenario.forbid_change and changed:
            return "no"
        if any(word.lower() not in spoken for word in scenario.reply_has):
            return "partial"
        if any(word.lower() in spoken for word in scenario.reply_lacks):
            return "no"
        return "yes"

    if scenario.expect_tool is None:
        # Ambiguous request. Not acting is the right answer.
        return "yes" if not calls else "no"

    if scenario.expect_refusal:
        # Calling the tool is correct. Actually doing the thing is not.
        if scenario.expect_tool in names:
            return "yes" if refused else "no"
        return "partial"

    if scenario.expect_tool not in names:
        return "no"

    # A command with more than one action in it is only done if every action
    # happened. Calling the first tool and talking about the second is a
    # failure, however confident the reply sounds.
    missing = [t for t in scenario.expect_tools if t not in names]
    if missing:
        return "partial" if len(missing) < len(scenario.expect_tools) else "no"

    if not scenario.expect_args:
        return "yes"

    got = next(c for c in calls if c["name"] == scenario.expect_tool)["arguments"]
    return "yes" if _args_match(scenario.expect_args, got) else "partial"


def _args_match(wanted: dict, got: dict) -> bool:
    """Loose match: spoken device names vary, numbers have to be right."""
    for key, want in wanted.items():
        have = got.get(key)
        if isinstance(want, str):
            if not isinstance(have, str):
                return False
            if want.lower() not in have.lower() and have.lower() not in want.lower():
                return False
        elif isinstance(want, (int, float)):
            try:
                if abs(float(have) - float(want)) > 0.01:
                    return False
            except (TypeError, ValueError):
                return False
        elif have != want:
            return False
    return True


def run_suite(repeat: int = 1, publish: bool = True, limit: int | None = None) -> dict:
    check_offline()
    home = Home()
    bridge = None

    if publish:
        try:
            bridge = MqttBridge(home, host=MQTT_HOST, port=MQTT_PORT)
            bridge.start()
        except ConnectionError as e:
            log.warning("no broker, running without the dashboard: %s", e)

    system_prompt = build_system_prompt(home)
    schema = openai_schema()
    results: list[Result] = []
    suite = SUITE[:limit] if limit else SUITE

    try:
        for pass_number in range(1, repeat + 1):
            for scenario in suite:
                results.append(_run_one(home, scenario, system_prompt, schema))
            if repeat > 1:
                print(f"  --- pass {pass_number} done ---")
    finally:
        if bridge:
            bridge.stop()

    return summarise(results, repeat)


def _run_one(home: Home, scenario: Scenario, system_prompt: str,
             schema: list[dict]) -> Result:
    result = Result(scenario=scenario.id, utterance=scenario.utterance,
                    note=scenario.note)

    home.begin_turn()
    audio, _ = engines.speak(scenario.utterance)
    result.transcript, result.asr_s = engines.transcribe(audio)
    calls, said, result.llm_ttft_s = engines.decide(
        system_prompt, result.transcript, schema
    )
    result.tool_calls = calls

    before = _snapshot(home)
    refused = False
    for call in calls:
        message, was_refused = run_tool(home, call["name"], call["arguments"])
        result.outcomes.append(message)
        refused = refused or was_refused
    changed = _snapshot(home) != before

    home.note_command(result.transcript)

    if calls:
        # The model often asks for the second half of a compound command only
        # after it has seen the first half succeed, so the tool runner is
        # handed to respond() and anything it calls counts towards the score.
        def follow_up(name: str, arguments: dict) -> str:
            nonlocal refused
            message, was_refused = run_tool(home, name, arguments)
            result.outcomes.append(message)
            refused = refused or was_refused
            return message

        result.reply, more, _, result.llm_reply_ttft_s = engines.respond(
            system_prompt, result.transcript, schema, calls, list(result.outcomes),
            run=follow_up,
        )
        if more:
            result.tool_calls = calls + more
        changed = _snapshot(home) != before
    else:
        result.reply = said.strip()
    _, result.tts_out_ttfb_s = engines.speak(result.reply or "Done.")
    # Every tool the turn ran, not just the first round. Passing `calls` here
    # meant a follow-up call could not affect the score, so the compound
    # scenario was being carried by the prompt alone while the code claimed
    # otherwise.
    result.intent = score(scenario, result.tool_calls, refused,
                          result.reply, changed)

    mark = {"yes": "OK  ", "partial": "PART", "no": "FAIL"}[result.intent]
    print(f"  [{mark}] {scenario.id:<16} {result.end_to_end_s:>6.3f}s  "
          f"{result.transcript}")
    return result


def _snapshot(home: Home) -> str:
    """Freeze the house, so we can tell whether a turn changed anything.

    The transcript sensor is left out. It records what was heard, so it changes
    on every turn including the ones where the right answer was to do nothing,
    and counting it made a scenario that correctly refused to unlock a door
    score as a failure for having changed the house.
    """
    return json.dumps(
        [entity.state for entity in home.all()
         if entity.entity_id != "sensor.last_command"],
        sort_keys=True,
    )


def _stats(values: list[float]) -> dict:
    """Mean and p95. The p95 is the interpolated one from `metrics`.

    An earlier version indexed `sorted(values)[int(n * 0.95) - 1]`, which for
    thirteen samples returns the eleventh, the 85th percentile, reported as the
    95th. Every p95 in every earlier result file is mislabelled for that
    reason.
    """
    return {
        "mean": round(statistics.fmean(values), 3),
        "p95": percentile(values, 0.95),
    }


def summarise(results: list[Result], repeat: int) -> dict:
    end_to_end = [r.end_to_end_s for r in results]
    counts = {verdict: sum(1 for r in results if r.intent == verdict)
              for verdict in ("yes", "partial", "no")}
    weighted = (counts["yes"] + 0.5 * counts["partial"]) / len(results)
    under_target = [t for t in end_to_end if t <= 2.0]

    return {
        "generated": datetime.now().isoformat(timespec="seconds"),
        "stack": {
            "asr": ASR_MODEL,
            "llm": LLM_MODEL,
            "tts": f"magpie/{TTS_VOICE}",
            "asr_server": ASR_SERVER,
            "tts_server": TTS_SERVER,
            "llm_base_url": LLM_BASE_URL,
        },
        "passes": repeat,
        "scenarios": len(results),
        "intent": {
            **counts,
            "weighted_success": round(weighted, 3),
            "target_0_90_met": weighted > 0.90,
        },
        "latency_s": {
            "asr": _stats([r.asr_s for r in results]),
            "llm_ttft": _stats([r.llm_ttft_s for r in results]),
            "llm_reply_ttft": _stats([r.llm_reply_ttft_s for r in results]),
            "tts_ttfb": _stats([r.tts_out_ttfb_s for r in results]),
            "end_to_end": {
                **_stats(end_to_end),
                "median": round(statistics.median(end_to_end), 3),
                "min": round(min(end_to_end), 3),
                "max": round(max(end_to_end), 3),
            },
        },
        "target_2s": {
            "met": len(under_target),
            "of": len(end_to_end),
            "rate": round(len(under_target) / len(end_to_end), 3),
        },
        "results": [{**r.__dict__, "end_to_end_s": r.end_to_end_s}
                    for r in results],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="HearthVoice evaluation harness")
    parser.add_argument("--repeat", type=int, default=1)
    parser.add_argument("--limit", type=int, default=None,
                        help="run only the first N scenarios. The egress test "
                             "uses 12, which is the suite as it was when that "
                             "measurement was first taken.")
    parser.add_argument("--no-publish", action="store_true",
                        help="measure without touching the dashboard")
    args = parser.parse_args()

    logging.basicConfig(level=logging.WARNING, format="%(message)s")
    n = min(args.limit, len(SUITE)) if args.limit else len(SUITE)
    print(f"\n  {n} scenarios x {args.repeat} pass(es), all models local\n")

    summary = run_suite(args.repeat, publish=not args.no_publish, limit=args.limit)

    EVAL_DIR.mkdir(parents=True, exist_ok=True)
    path = EVAL_DIR / f"harness_{datetime.now():%Y%m%d_%H%M%S}.json"
    path.write_text(json.dumps(summary, indent=2))

    intent = summary["intent"]
    latency = summary["latency_s"]
    target = summary["target_2s"]
    print(f"\n  intent   yes {intent['yes']}  partial {intent['partial']}  "
          f"no {intent['no']}   weighted {intent['weighted_success']:.1%}")
    print(f"  latency  asr {latency['asr']['mean']}s  "
          f"llm {latency['llm_ttft']['mean']}s  tts {latency['tts_ttfb']['mean']}s")
    print(f"  end to end  mean {latency['end_to_end']['mean']}s  "
          f"median {latency['end_to_end']['median']}s  "
          f"p95 {latency['end_to_end']['p95']}s")
    print(f"  under 2 s   {target['met']}/{target['of']} ({target['rate']:.0%})")
    print(f"\n  written to {path}\n")


if __name__ == "__main__":
    main()
